### ISSUE TITLE
[DOCS] Testing page does not load

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#1340]
**Scope**: Docs

**Description**

[Testing page](https://data-driven-forms.org/testing) does not load in deployed version

![image](https://user-images.githubusercontent.com/32869456/200803501-6998b3d5-d5d9-4cce-bcb9-bdd5a8230ced.png)

```jsx
       TypeError: Cannot read properties of null (reading 'length')
    at e (_app-bbc7c2f99276f992.js:89:20186)
    at e (_app-bbc7c2f99276f992.js:89:20645)
    at e (_app-bbc7c2f99276f992.js:89:20645)
    at Object.tokenize (_app-bbc7c2f99276f992.js:89:20708)
    at t.tokenize (_app-bbc7c2f99276f992.js:89:89572)
    at t.render (_app-bbc7c2f99276f992.js:89:89906)
    at uP (framework-e4fb016042086091.js:9:76295)
    at u8 (framework-e4fb016042086091.js:9:76093)
    at i (framework-e4fb016042086091.js:9:120720)
    at oq (framework-e4fb016042086091.js:9:107174)
```

**Comment by Fewwy** [comment]
The issue is still there :)

**Comment by rvsia** [comment]
Yeah, but it should go away when we migrate to Vercel.

**Comment by Hyperkid123** [comment]
I've just changed the DNS settings in our domain provider. It should take about 60 minutes to take an effect.

**Comment by Hyperkid123** [comment]
@rvsia @Fewwy https://www.data-driven-forms.org/testing should work again. You might need to clear your cache. The domain should be changed now.

**Comment by rvsia** [comment]
@Hyperkid123 awesome, works for me! 👍  😊

**Comment by Fewwy** [comment]
@Hyperkid123 @rvsia Thanks, now it works!
